[package]
name = "zkube"
version = "0.0.0"
edition = "2023_10"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo --profile dev clean && sozo --profile dev build && sozo --profile dev migrate plan && sozo --profile dev migrate apply"
sepolia = "NAME=zkube-v2 && sozo --profile sepolia clean && sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate plan --name $NAME && sozo --profile sepolia migrate apply --fee-estimate-multiplier 10 --verbose  --name $NAME"


[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "78b0d51" }
origami = { git = "https://github.com/dojoengine/origami", tag = "v0.7.2" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.2" }
stark_vrf = { git = "https://github.com/dojoengine/stark-vrf", rev = "5a9e81e" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[profile.dev.tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x6b86e40118f29ebe393a75469b4d926c7a44c2e2681b6d319520b7c1156d114"
private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"

[profile.slot.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/zkube/katana"
account_address = "0x1c10815b8e3fb0830a702eddb77a566ee78e3d173557bf3ed7b9a8b28f048ca"
private_key = "0x4b5b87f25c379f5f5088cc4b14fe7963dfc7675cfdb94e1c263a849f3c2b9d3"

[profile.sepolia.tool.dojo.env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
account_address = "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7"
private_key = "0x9a2816a70849c36ce6ef74a8b5d8007e40f36f3e96d1ce72d2bced106e8b1f"

[tool.dojo.world]
name = "zKube"
description = "Solo strategy card game where you manage resources and upgrade your village to maximize points. Make tactical decisions to help your village grow and flourish."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://app.zkube.xyz"

[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
