kind = "DojoContract"
class_hash = "0x2410bd6a43a0a2a48e18fadf3c5b4d16b070230fef8c865b1952ce26c105f97"
original_class_hash = "0x2410bd6a43a0a2a48e18fadf3c5b4d16b070230fef8c865b1952ce26c105f97"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
